# Importing Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

## Reading Data

In [2]:
sample_sub = pd.read_csv(r"D:\Data Science Course\Projects\Analytics vidya\Big Mart Sales Prediction\sample_submission_8RXa3c6.csv")
train = pd.read_csv(r"D:\Data Science Course\Projects\Analytics vidya\Big Mart Sales Prediction\train_v9rqX0R.csv")
test = pd.read_csv(r"D:\Data Science Course\Projects\Analytics vidya\Big Mart Sales Prediction\test_AbJTz2l.csv")

In [3]:
print('Shape of train data: {}'.format(train.shape))
print('Shape of test data: {}'.format(test.shape))

Shape of train data: (8523, 12)
Shape of test data: (5681, 11)

In [4]:
train.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.30,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.92,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.50,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.20,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.93,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052

# Feature Dictionary
Item_Identifier : Unique product ID (Informative)

Item_Weight : Weight of product (Continuous)

Item_Fat_Content : Whether the product is low fat or not (Categorical)

Item_Visibility : The % of total display area of all products in a store allocated to the particular product (Continuous)

Item_Type : The category to which the product belongs (Categorical)

Item_MRP : Maximum Retail Price (list price) of the product (Continuous)

Outlet_Identifier : Unique store ID (Informative)

Outlet_Establishment_Year : The year in which store was established (Informative - Descrete)

Outlet_Size : The size of the store in terms of ground area covered (Categorical)

Outlet_Location_Type : The type of city in which the store is located (Categorical)

Outlet_Type : Whether the outlet is just a grocery store or some sort of supermarket (Categorical)

Item_Outlet_Sales : Sales of the product in the particular store. This is the outcome variable to be predicted. (Target)

In [5]:
train.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.30,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.92,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.50,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.20,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.93,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052

In [6]:
sample_sub.head()

  Item_Identifier Outlet_Identifier  Item_Outlet_Sales
0           FDW58            OUT049               1000
1           FDW14            OUT017               1000
2           NCN55            OUT010               1000
3           FDQ58            OUT017               1000
4           FDY38            OUT027               1000

In [7]:
train['is_train'] = 1
test['is_train'] = 0
test['Item_Outlet_Sales'] = None

In [8]:
data = pd.concat((train,test))

In [9]:
data.shape

(14204, 13)

# ML Pipeline

### Missing Values

In [10]:
data.isna().sum()/data.shape[0]*100

Item_Identifier               0.000000
Item_Weight                  17.171219
Item_Fat_Content              0.000000
Item_Visibility               0.000000
Item_Type                     0.000000
Item_MRP                      0.000000
Outlet_Identifier             0.000000
Outlet_Establishment_Year     0.000000
Outlet_Size                  28.273726
Outlet_Location_Type          0.000000
Outlet_Type                   0.000000
Item_Outlet_Sales            39.995776
is_train                      0.000000
dtype: float64

In [11]:
weight_dict = data.groupby('Item_Identifier')['Item_Weight'].median().to_dict()

In [12]:
weight_dict

{'DRA12': 11.6,
 'DRA24': 19.35,
 'DRA59': 8.27,
 'DRB01': 7.39,
 'DRB13': 6.115,
 'DRB24': 8.785,
 'DRB25': 12.3,
 'DRB48': 16.75,
 'DRC01': 5.92,
 'DRC12': 17.85,
 'DRC13': 8.26,
 'DRC24': 17.85,
 'DRC25': 5.73,
 'DRC27': 13.8,
 'DRC36': 13.0,
 'DRC49': 8.67,
 'DRD01': 12.1,
 'DRD12': 6.96,
 'DRD13': 15.0,
 'DRD15': 10.6,
 'DRD24': 13.85,
 'DRD25': 6.135,
 'DRD27': 18.75,
 'DRD37': 9.8,
 'DRD49': 9.895,
 'DRD60': 15.7,
 'DRE01': 10.1,
 'DRE03': 19.6,
 'DRE12': 4.59,
 'DRE13': 6.28,
 'DRE15': 13.35,
 'DRE25': 15.35,
 'DRE27': 11.85,
 'DRE37': 13.5,
 'DRE48': 8.43,
 'DRE49': 20.75,
 'DRE60': 9.395,
 'DRF01': 5.655,
 'DRF03': 19.1,
 'DRF13': 12.1,
 'DRF15': 18.35,
 'DRF23': 4.61,
 'DRF25': 9.0,
 'DRF27': 8.93,
 'DRF36': 16.1,
 'DRF37': 17.25,
 'DRF48': 5.73,
 'DRF49': 7.27,
 'DRF51': 15.75,
 'DRF60': 10.8,
 'DRG01': 14.8,
 'DRG03': 14.5,
 'DRG11': 6.385,
 'DRG13': 17.25,
 'DRG15': 6.13,
 'DRG23': 8.88,
 'DRG25': 10.5,
 'DRG27': 8.895,
 'DRG36': 14.15,
 'DRG37': 16.2,
 'DRG39': 14.15,
 'DRG48': 5.78,
 'DRG49': 7.81,
 'DRG51': 12.1,
 'DRH01': 17.5,
 'DRH03': 17.25,
 'DRH11': 5.98,
 'DRH13': 8.575,
 'DRH15': 8.775,
 'DRH23': 14.65,
 'DRH25': 18.7,
 'DRH36': 16.2,
 'DRH37': 17.6,
 'DRH39': 20.7,
 'DRH49': 19.7,
 'DRH51': 17.6,
 'DRH59': 10.8,
 'DRI01': 7.97,
 'DRI03': 6.03,
 'DRI11': 8.26,
 'DRI13': 15.35,
 'DRI23': 18.85,
 'DRI25': 19.6,
 'DRI37': 15.85,
 'DRI39': 13.8,
 'DRI47': 14.7,
 'DRI49': 14.15,
 'DRI51': 17.25,
 'DRI59': 9.5,
 'DRJ01': 6.135,
 'DRJ11': 9.5,
 'DRJ13': 12.65,
 'DRJ23': 18.35,
 'DRJ24': 11.8,
 'DRJ25': 14.6,
 'DRJ35': 10.1,
 'DRJ37': 10.8,
 'DRJ39': 20.25,
 'DRJ47': 18.25,
 'DRJ49': 6.865,
 'DRJ51': 14.1,
 'DRJ59': 11.65,
 'DRK01': 7.63,
 'DRK11': 8.21,
 'DRK12': 9.5,
 'DRK13': 11.8,
 'DRK23': 8.395,
 'DRK35': 8.365,
 'DRK37': 5.0,
 'DRK39': 7.02,
 'DRK47': 7.905,
 'DRK49': 14.15,
 'DRK59': 8.895,
 'DRL01': 19.5,
 'DRL11': 10.5,
 'DRL23': 18.35,
 'DRL35': 15.7,
 'DRL37': 15.5,
 'DRL47': 19.7,
 'DRL49': 13.15,
 'DRL59': 16.75,
 'DRL60': 8.52,
 'DRM11': 6.57,
 'DRM23': 16.6,
 'DRM35': 9.695,
 'DRM37': 15.35,
 'DRM47': 9.3,
 'DRM48': 15.2,
 'DRM49': 6.11,
 'DRM59': 5.88,
 'DRN11': 7.85,
 'DRN35': 8.01,
 'DRN36': 15.2,
 'DRN37': 9.6,
 'DRN47': 12.1,
 'DRN59': 15.0,
 'DRO35': 13.85,
 'DRO47': 10.195,
 'DRO59': 11.8,
 'DRP35': 18.85,
 'DRP47': 15.75,
 'DRQ35': 9.3,
 'DRY23': 9.395,
 'DRZ11': 8.85,
 'DRZ24': 7.535,
 'FDA01': 15.0,
 'FDA02': 14.0,
 'FDA03': 18.5,
 'FDA04': 11.3,
 'FDA07': 7.55,
 'FDA08': 11.85,
 'FDA09': 13.35,
 'FDA10': 20.35,
 'FDA11': 7.75,
 'FDA13': 15.85,
 'FDA14': 16.1,
 'FDA15': 9.3,
 'FDA16': 6.695,
 'FDA19': 7.52,
 'FDA20': 6.78,
 'FDA21': 13.65,
 'FDA22': 7.435,
 'FDA23': 9.8,
 'FDA25': 16.5,
 'FDA26': 7.855,
 'FDA27': 20.35,
 'FDA28': 16.1,
 'FDA31': 7.1,
 'FDA32': 14.0,
 'FDA33': 6.48,
 'FDA34': 11.5,
 'FDA35': 14.85,
 'FDA36': 5.985,
 'FDA37': 7.81,
 'FDA38': 5.44,
 'FDA39': 6.32,
 'FDA40': 16.0,
 'FDA43': 10.895,
 'FDA44': 19.7,
 'FDA45': 21.25,
 'FDA46': 13.6,
 'FDA47': 10.5,
 'FDA48': 12.1,
 'FDA49': 19.7,
 'FDA50': 16.25,
 'FDA51': 8.05,
 'FDA52': 16.2,
 'FDA55': 17.2,
 'FDA56': 9.21,
 'FDA57': 18.85,
 'FDA58': 9.395,
 'FDB02': 9.695,
 'FDB03': 17.75,
 'FDB04': 11.35,
 'FDB05': 5.155,
 'FDB08': 6.055,
 'FDB09': 16.25,
 'FDB10': 10.0,
 'FDB11': 16.0,
 'FDB12': 11.15,
 'FDB14': 20.25,
 'FDB15': 10.895,
 'FDB16': 8.21,
 'FDB17': 13.15,
 'FDB20': 7.72,
 'FDB21': 7.475,
 'FDB22': 8.02,
 'FDB23': 19.2,
 'FDB26': 14.0,
 'FDB27': 7.575,
 'FDB28': 6.615,
 'FDB29': 16.7,
 'FDB32': 20.6,
 'FDB33': 17.75,
 'FDB34': 15.25,
 'FDB35': 12.3,
 'FDB36': 5.465,
 'FDB37': 20.25,
 'FDB38': 19.5,
 'FDB39': 11.6,
 'FDB40': 17.5,
 'FDB41': 19.0,
 'FDB44': 6.655,
 'FDB45': 20.85,
 'FDB46': 10.5,
 'FDB47': 8.8,
 'FDB49': 8.3,
 'FDB50': 13.0,
 'FDB51': 6.92,
 'FDB52': 17.75,
 'FDB53': 13.35,
 'FDB56': 8.75,
 'FDB57': 20.25,
 'FDB58': 10.5,
 'FDB59': 18.25,
 'FDB60': 9.3,
 'FDC02': 21.35,
 'FDC03': 8.575,
 'FDC04': 15.6,
 'FDC05': 13.1,
 'FDC08': 19.0,
 'FDC09': 15.5,
 'FDC10': 9.8,
 'FDC11': 20.5,
 'FDC14': 14.5,
 'FDC15': 18.1,
 'FDC16': 11.5,
 'FDC17': 12.15,
 'FDC20': 10.65,
 'FDC21': 14.6,
 'FDC22': 6.89,
 'FDC23': 18.0,
 'FDC26': 10.195,
 'FDC28': 7.905,
 'FDC29': 8.39,
 'FDC32': 18.35,
 'FDC33': 8.96,
 'FDC34': 16.0,
 'FDC35': 7.435,
 'FDC37': 15.5,
 'FDC38': 15.7,
 'FDC39': 7.405,
 'FDC40': 16.0,
 'FDC41': 15.6,
 'FDC44': 15.6,
 'FDC45': 17.0,
 'FDC46': 17.7,
 'FDC47': 15.0,
 'FDC48': 9.195,
 'FDC50': 15.85,
 'FDC51': 10.895,
 'FDC52': 11.15,
 'FDC53': 8.68,
 'FDC56': 7.72,
 'FDC57': 20.1,
 'FDC58': 10.195,
 'FDC59': 16.7,
 'FDC60': 5.425,
 'FDD02': 16.6,
 'FDD03': 13.3,
 'FDD04': 16.0,
 'FDD05': 19.35,
 'FDD08': 8.3,
 'FDD09': 13.5,
 'FDD10': 20.6,
 'FDD11': 12.85,
 'FDD14': 20.7,
 'FDD16': 20.5,
 'FDD17': 7.5,
 'FDD20': 14.15,
 'FDD21': 10.3,
 'FDD22': 10.0,
 'FDD23': 9.5,
 'FDD26': 8.71,
 'FDD28': 10.695,
 'FDD29': 12.15,
 'FDD32': 17.7,
 'FDD33': 12.85,
 'FDD34': 7.945,
 'FDD35': 12.15,
 'FDD36': 13.3,
 'FDD38': 16.75,
 'FDD39': 16.7,
 'FDD40': 20.25,
 'FDD41': 6.765,
 'FDD44': 8.05,
 'FDD45': 8.615,
 'FDD46': 6.035,
 'FDD47': 7.6,
 'FDD48': 10.395,
 'FDD50': 18.85,
 'FDD51': 11.15,
 'FDD52': 18.25,
 'FDD53': 16.2,
 'FDD56': 15.2,
 'FDD57': 18.1,
 'FDD58': 7.76,
 'FDD59': 10.5,
 'FDE02': 8.71,
 'FDE04': 19.75,
 'FDE05': 10.895,
 'FDE08': 18.2,
 'FDE09': 8.775,
 'FDE10': 6.67,
 'FDE11': 17.7,
 'FDE14': 13.65,
 'FDE16': 8.895,
 'FDE17': 20.1,
 'FDE20': 11.35,
 'FDE21': 12.8,
 'FDE22': 9.695,
 'FDE23': 17.6,
 'FDE24': 14.85,
 'FDE26': 9.3,
 'FDE28': 9.5,
 'FDE29': 8.905,
 'FDE32': 20.7,
 'FDE33': 19.35,
 'FDE34': 9.195,
 'FDE35': 7.06,
 'FDE36': 5.26,
 'FDE38': 6.52,
 'FDE39': 7.89,
 'FDE40': 15.6,
 'FDE41': 9.195,
 'FDE44': 14.65,
 'FDE45': 12.1,
 'FDE46': 18.6,
 'FDE47': 14.15,
 'FDE50': 19.7,
 'FDE51': 5.925,
 'FDE52': 10.395,
 'FDE53': 10.895,
 'FDE56': 17.25,
 'FDE57': 9.6,
 'FDE58': 18.5,
 'FDE59': 12.15,
 'FDF02': 16.2,
 'FDF04': 17.5,
 'FDF05': 17.5,
 'FDF08': 14.3,
 'FDF09': 6.215,
 'FDF10': 15.5,
 'FDF11': 10.195,
 'FDF12': 8.235,
 'FDF14': 7.55,
 'FDF16': 7.3,
 'FDF17': 5.19,
 'FDF20': 12.85,
 'FDF21': 10.3,
 'FDF22': 6.865,
 'FDF24': 15.5,
 'FDF26': 6.825,
 'FDF28': 15.7,
 'FDF29': 15.1,
 'FDF32': 16.35,
 'FDF33': 7.97,
 'FDF34': 9.3,
 'FDF35': 15.0,
 'FDF38': 11.8,
 'FDF39': 14.85,
 'FDF40': 20.25,
 'FDF41': 12.15,
 'FDF44': 7.17,
 'FDF45': 18.2,
 'FDF46': 7.07,
 'FDF47': 20.85,
 'FDF50': 4.905,
 'FDF52': 9.3,
 'FDF53': 20.75,
 'FDF56': 16.7,
 'FDF57': 14.5,
 'FDF58': 13.3,
 'FDF59': 12.5,
 'FDG02': 7.855,
 'FDG04': 13.1,
 'FDG05': 11.0,
 'FDG08': 13.15,
 'FDG09': 20.6,
 'FDG10': 6.63,
 'FDG12': 6.635,
 'FDG14': 9.0,
 'FDG16': 15.25,
 'FDG17': 6.865,
 'FDG20': 15.5,
 'FDG21': 17.35,
 'FDG22': 17.6,
 'FDG24': 7.975,
 'FDG26': 18.85,
 'FDG28': 9.285,
 'FDG29': 17.6,
 'FDG31': 12.15,
 'FDG32': 19.85,
 'FDG33': 5.365,
 'FDG34': 11.5,
 'FDG35': 21.2,
 'FDG38': 8.975,
 'FDG40': 13.65,
 'FDG41': 8.84,
 'FDG44': 6.13,
 'FDG45': 8.1,
 'FDG46': 8.63,
 'FDG47': 12.8,
 'FDG50': 7.405,
 'FDG52': 13.65,
 'FDG53': 10.0,
 'FDG56': 13.3,
 'FDG57': 14.7,
 'FDG58': 10.695,
 'FDG59': 15.85,
 'FDG60': 20.35,
 'FDH02': 7.27,
 'FDH04': 6.115,
 'FDH05': 14.35,
 'FDH08': 7.51,
 'FDH09': 12.6,
 'FDH10': 21.0,
 'FDH12': 9.6,
 'FDH14': 17.1,
 'FDH16': 10.5,
 'FDH17': 16.2,
 'FDH19': 19.35,
 'FDH20': 16.1,
 'FDH21': 10.395,
 'FDH22': 6.405,
 'FDH24': 20.7,
 'FDH26': 19.25,
 'FDH27': 7.075,
 'FDH28': 15.85,
 'FDH31': 12.0,
 'FDH32': 12.8,
 'FDH33': 12.85,
 'FDH34': 8.63,
 'FDH35': 18.25,
 'FDH38': 6.425,
 'FDH40': 11.6,
 'FDH41': 9.0,
 'FDH44': 19.1,
 'FDH45': 15.1,
 'FDH46': 6.935,
 'FDH47': 13.5,
 'FDH48': 13.5,
 'FDH50': 15.0,
 'FDH52': 9.42,
 'FDH53': 20.5,
 'FDH56': 9.8,
 'FDH57': 10.895,
 'FDH58': 12.3,
 'FDH60': 19.7,
 'FDI02': 15.7,
 'FDI04': 13.65,
 'FDI05': 8.35,
 'FDI07': 12.35,
 'FDI08': 18.2,
 'FDI09': 20.75,
 'FDI10': 8.51,
 'FDI12': 9.395,
 'FDI14': 14.1,
 'FDI15': 13.8,
 'FDI16': 14.0,
 'FDI19': 15.1,
 'FDI20': 19.1,
 'FDI21': 5.59,
 'FDI22': 12.6,
 'FDI24': 10.3,
 'FDI26': 5.94,
 'FDI27': 8.71,
 'FDI28': 14.3,
 'FDI32': 17.7,
 'FDI33': 16.5,
 'FDI34': 10.65,
 'FDI35': 14.0,
 'FDI36': 12.5,
 'FDI38': 13.35,
 'FDI40': 11.5,
 'FDI41': 18.5,
 'FDI44': 16.1,
 'FDI45': 13.1,
 'FDI46': 9.5,
 'FDI48': 11.85,
 'FDI50': 8.42,
 'FDI52': 18.7,
 'FDI53': 8.895,
 'FDI56': 7.325,
 'FDI57': 19.85,
 'FDI58': 7.64,
 'FDI60': 7.22,
 'FDJ02': 17.2,
 'FDJ03': 12.35,
 'FDJ04': 18.0,
 'FDJ07': 7.26,
 'FDJ08': 11.1,
 'FDJ09': 15.0,
 'FDJ10': 5.095,
 'FDJ12': 8.895,
 'FDJ14': 10.3,
 'FDJ15': 11.35,
 'FDJ16': 9.195,
 'FDJ20': 20.7,
 'FDJ21': 16.7,
 'FDJ22': 18.75,
 'FDJ26': 15.3,
 'FDJ27': 17.7,
 'FDJ28': 12.3,
 'FDJ32': 10.695,
 'FDJ33': 8.895,
 'FDJ34': 11.8,
 'FDJ36': 14.5,
 'FDJ38': 8.6,
 'FDJ40': 13.6,
 'FDJ41': 6.85,
 'FDJ44': 12.3,
 'FDJ45': 17.75,
 'FDJ46': 11.1,
 'FDJ48': 11.3,
 'FDJ50': 8.645,
 'FDJ52': 7.145,
 'FDJ53': 10.5,
 'FDJ55': 12.8,
 'FDJ56': 8.985,
 'FDJ57': 7.42,
 'FDJ58': 15.6,
 'FDJ60': 19.35,
 'FDK02': 12.5,
 'FDK03': 12.6,
 'FDK04': 7.36,
 'FDK08': 9.195,
 'FDK09': 15.2,
 'FDK10': 5.785,
 'FDK14': 6.98,
 'FDK15': 10.8,
 'FDK16': 9.065,
 'FDK20': 12.6,
 'FDK21': 7.905,
 'FDK22': 9.8,
 'FDK24': 9.195,
 'FDK25': 11.6,
 'FDK26': 5.46,
 'FDK27': 11.0,
 'FDK28': 5.695,
 'FDK32': 16.25,
 'FDK33': 17.85,
 'FDK34': 13.35,
 'FDK36': 7.09,
 'FDK38': 6.65,
 'FDK40': 7.035,
 'FDK41': 14.3,
 'FDK43': 9.8,
 'FDK44': 16.6,
 'FDK45': 11.65,
 'FDK46': 9.6,
 'FDK48': 7.445,
 'FDK50': 7.96,
 'FDK51': 19.85,
 'FDK52': 18.25,
 'FDK55': 18.5,
 'FDK56': 9.695,
 'FDK57': 10.195,
 'FDK58': 11.35,
 'FDK60': 16.5,
 'FDL02': 20.0,
 'FDL03': 19.25,
 'FDL04': 19.0,
 'FDL08': 10.8,
 'FDL09': 19.6,
 'FDL10': 8.395,
 'FDL12': 15.85,
 'FDL13': 13.85,
 'FDL14': 8.115,
 'FDL15': 17.85,
 'FDL16': 12.85,
 'FDL20': 17.1,
 'FDL21': 15.85,
 'FDL22': 16.85,
 'FDL24': 10.3,
 'FDL25': 6.92,
 'FDL26': 18.0,
 'FDL27': 6.17,
 'FDL28': 10.0,
 'FDL32': 15.7,
 'FDL33': 7.235,
 'FDL34': 16.0,
 'FDL36': 15.1,
 'FDL38': 13.8,
 'FDL39': 16.1,
 'FDL40': 17.7,
 'FDL43': 10.1,
 'FDL44': 18.25,
 'FDL45': 15.6,
 'FDL46': 20.35,
 'FDL48': 19.35,
 'FDL50': 12.15,
 'FDL51': 20.7,
 'FDL52': 6.635,
 'FDL56': 14.1,
 'FDL57': 15.1,
 'FDL58': 5.78,
 'FDM01': 7.895,
 'FDM02': 12.5,
 'FDM03': 12.65,
 'FDM04': 9.195,
 'FDM08': 10.1,
 'FDM09': 11.15,
 'FDM10': 18.25,
 'FDM12': 16.7,
 'FDM13': 6.425,
 'FDM14': 13.8,
 'FDM15': 11.8,
 'FDM16': 8.155,
 'FDM20': 10.0,
 'FDM21': 20.2,
 'FDM22': 14.0,
 'FDM24': 6.135,
 'FDM25': 10.695,
 'FDM27': 12.35,
 'FDM28': 15.7,
 'FDM32': 20.5,
 'FDM33': 15.6,
 'FDM34': 19.0,
 'FDM36': 11.65,
 'FDM38': 5.885,
 'FDM39': 6.42,
 'FDM40': 10.195,
 'FDM44': 12.5,
 'FDM45': 8.655,
 'FDM46': 7.365,
 'FDM50': 13.0,
 'FDM51': 11.8,
 'FDM52': 15.1,
 'FDM56': 16.7,
 'FDM57': 11.65,
 'FDM58': 16.85,
 'FDM60': 10.8,
 'FDN01': 8.895,
 'FDN02': 16.5,
 'FDN03': 9.8,
 'FDN04': 11.8,
 'FDN08': 7.72,
 'FDN09': 14.15,
 'FDN10': 11.5,
 'FDN12': 15.6,
 'FDN13': 18.6,
 'FDN15': 17.5,
 'FDN16': 12.6,
 'FDN20': 19.35,
 'FDN21': 18.6,
 'FDN22': 18.85,
 'FDN23': 6.575,
 'FDN24': 14.1,
 'FDN25': 7.895,
 'FDN27': 20.85,
 'FDN28': 5.88,
 'FDN31': 11.5,
 'FDN32': 17.5,
 'FDN33': 6.305,
 'FDN34': 15.6,
 'FDN38': 6.615,
 'FDN39': 19.35,
 'FDN40': 5.88,
 'FDN44': 13.15,
 'FDN45': 19.35,
 'FDN46': 7.21,
 'FDN48': 13.35,
 'FDN49': 17.25,
 'FDN50': 16.85,
 'FDN51': 17.85,
 'FDN52': 9.395,
 'FDN56': 5.46,
 'FDN57': 18.25,
 'FDN58': 13.8,
 'FDN60': 15.1,
 'FDO01': 21.1,
 'FDO03': 10.395,
 'FDO04': 16.6,
 'FDO08': 11.1,
 'FDO09': 13.5,
 'FDO10': 13.65,
 'FDO11': 8.0,
 'FDO12': 15.75,
 'FDO13': 7.865,
 'FDO15': 16.75,
 'FDO16': 5.48,
 'FDO19': 17.7,
 'FDO20': 12.85,
 'FDO21': 11.6,
 'FDO22': 13.5,
 'FDO23': 17.85,
 'FDO24': 11.1,
 'FDO25': 6.3,
 'FDO27': 6.175,
 'FDO28': 5.765,
 'FDO31': 6.76,
 'FDO32': 6.36,
 'FDO33': 14.75,
 'FDO34': 17.7,
 'FDO36': 19.7,
 'FDO37': 8.06,
 'FDO38': 17.25,
 'FDO39': 6.985,
 'FDO40': 17.1,
 'FDO44': 12.6,
 'FDO45': 13.15,
 'FDO46': 9.6,
 'FDO48': 15.0,
 'FDO49': 10.6,
 'FDO50': 16.25,
 'FDO51': 6.785,
 'FDO52': 11.6,
 'FDO56': 10.195,
 'FDO57': 20.75,
 'FDO58': 19.6,
 'FDO60': 20.0,
 'FDP01': 20.75,
 'FDP03': 5.15,
 'FDP04': 15.35,
 'FDP07': 18.2,
 'FDP08': 20.5,
 'FDP09': 19.75,
 'FDP10': 19.0,
 'FDP11': 15.85,
 'FDP12': 9.8,
 'FDP13': 8.1,
 'FDP15': 15.2,
 'FDP16': 18.6,
 'FDP19': 11.5,
 'FDP20': 19.85,
 'FDP21': 7.42,
 'FDP22': 14.65,
 'FDP23': 6.71,
 'FDP24': 20.6,
 'FDP25': 15.2,
 'FDP26': 7.785,
 'FDP27': 8.155,
 'FDP28': 13.65,
 'FDP31': 21.1,
 'FDP32': 6.65,
 'FDP33': 18.7,
 'FDP34': 12.85,
 'FDP36': 10.395,
 'FDP37': 15.6,
 'FDP38': 10.1,
 'FDP39': 12.65,
 'FDP40': 4.555,
 'FDP44': 16.5,
 'FDP45': 15.7,
 'FDP46': 15.35,
 'FDP48': 7.52,
 'FDP49': 9.0,
 'FDP51': 13.85,
 'FDP52': 18.7,
 'FDP56': 8.185,
 'FDP57': 17.5,
 'FDP58': 11.1,
 'FDP59': 20.85,
 'FDP60': 17.35,
 'FDQ01': 19.7,
 'FDQ03': 15.0,
 'FDQ04': 6.4,
 'FDQ07': 15.1,
 'FDQ08': 15.7,
 'FDQ09': 7.235,
 'FDQ10': 12.85,
 'FDQ11': 5.695,
 'FDQ12': 12.65,
 'FDQ13': 11.1,
 'FDQ14': 9.27,
 'FDQ15': 20.35,
 'FDQ16': 19.7,
 'FDQ19': 7.35,
 'FDQ20': 8.325,
 'FDQ21': 21.25,
 'FDQ22': 16.75,
 'FDQ23': 6.55,
 'FDQ24': 15.7,
 'FDQ25': 8.63,
 'FDQ26': 13.5,
 'FDQ27': 5.19,
 'FDQ28': 14.0,
 'FDQ31': 5.785,
 'FDQ32': 17.85,
 'FDQ33': 13.35,
 'FDQ34': 10.85,
 'FDQ36': 7.855,
 'FDQ37': 20.75,
 'FDQ39': 14.8,
 'FDQ40': 11.1,
 'FDQ44': 20.5,
 'FDQ45': 9.5,
 'FDQ46': 7.51,
 'FDQ47': 7.155,
 'FDQ48': 14.3,
 'FDQ49': 20.2,
 'FDQ51': 16.0,
 'FDQ52': 17.0,
 'FDQ55': 13.65,
 'FDQ56': 6.59,
 'FDQ57': 7.275,
 'FDQ58': 7.315,
 'FDQ59': 9.8,
 'FDQ60': 6.195,
 'FDR01': 5.405,
 'FDR02': 16.7,
 'FDR03': 15.7,
 'FDR04': 7.075,
 'FDR07': 21.35,
 'FDR08': 18.7,
 'FDR09': 18.25,
 'FDR10': 17.6,
 'FDR11': 10.5,
 'FDR12': 12.6,
 'FDR13': 9.895,
 'FDR14': 11.65,
 'FDR15': 9.3,
 'FDR16': 5.845,
 'FDR19': 13.5,
 'FDR20': 20.0,
 'FDR21': 19.7,
 'FDR22': 19.35,
 'FDR23': 15.85,
 'FDR24': 17.35,
 'FDR25': 17.0,
 'FDR26': 20.7,
 'FDR27': 15.1,
 'FDR28': 13.85,
 'FDR31': 6.46,
 'FDR32': 6.78,
 'FDR33': 7.31,
 'FDR34': 17.0,
 'FDR35': 12.5,
 'FDR36': 6.715,
 'FDR37': 16.5,
 'FDR39': 20.35,
 'FDR40': 9.1,
 'FDR43': 18.2,
 'FDR44': 6.11,
 'FDR45': 10.8,
 'FDR46': 16.85,
 'FDR47': 17.85,
 'FDR48': 11.65,
 'FDR49': 8.71,
 'FDR51': 9.035,
 'FDR52': 12.65,
 'FDR55': 12.15,
 'FDR56': 15.5,
 'FDR57': 5.675,
 'FDR58': 6.675,
 'FDR59': 14.5,
 'FDR60': 14.3,
 'FDS01': 11.6,
 'FDS02': 10.195,
 'FDS03': 7.825,
 'FDS04': 10.195,
 'FDS07': 12.35,
 'FDS08': 5.735,
 'FDS09': 8.895,
 'FDS10': 19.2,
 'FDS11': 7.05,
 'FDS12': 9.1,
 'FDS13': 6.465,
 'FDS14': 7.285,
 'FDS15': 9.195,
 'FDS16': 15.15,
 'FDS19': 13.8,
 'FDS20': 8.85,
 'FDS21': 19.85,
 'FDS22': 16.85,
 'FDS23': 4.635,
 'FDS24': 20.85,
 'FDS25': 6.885,
 'FDS26': 20.35,
 'FDS27': 10.195,
 'FDS28': 8.18,
 'FDS31': 13.1,
 'FDS32': 17.75,
 'FDS33': 6.67,
 'FDS34': 19.35,
 'FDS35': 9.3,
 'FDS36': 8.38,
 'FDS37': 7.655,
 'FDS39': 6.895,
 'FDS40': 15.35,
 'FDS43': 11.65,
 'FDS44': 12.65,
 'FDS45': 5.175,
 'FDS46': 17.6,
 'FDS47': 16.75,
 'FDS48': 15.15,
 'FDS49': 9.0,
 'FDS50': 17.0,
 'FDS51': 13.35,
 'FDS52': 8.89,
 'FDS55': 7.02,
 'FDS56': 5.785,
 'FDS57': 15.5,
 'FDS58': 9.285,
 'FDS59': 14.8,
 'FDS60': 20.85,
 'FDT01': 13.65,
 'FDT02': 12.6,
 'FDT03': 21.25,
 'FDT04': 17.25,
 'FDT07': 5.82,
 'FDT08': 13.65,
 'FDT09': 15.15,
 'FDT10': 16.7,
 'FDT11': 5.94,
 'FDT12': 6.215,
 'FDT13': 14.85,
 'FDT14': 10.695,
 'FDT15': 12.15,
 'FDT16': 9.895,
 'FDT19': 7.59,
 'FDT20': 10.5,
 'FDT21': 7.42,
 'FDT22': 10.395,
 'FDT23': 7.72,
 'FDT24': 12.35,
 'FDT25': 7.5,
 'FDT26': 18.85,
 'FDT27': 11.395,
 'FDT28': 13.3,
 'FDT31': 19.75,
 'FDT32': 19.0,
 'FDT33': 7.81,
 'FDT34': 9.3,
 'FDT35': 19.85,
 'FDT36': 12.3,
 'FDT37': 14.15,
 'FDT38': 18.7,
 'FDT39': 6.26,
 'FDT40': 5.985,
 'FDT43': 16.35,
 'FDT44': 16.6,
 'FDT45': 15.85,
 'FDT46': 11.35,
 'FDT47': 5.26,
 'FDT48': 4.92,
 'FDT49': 7.0,
 'FDT50': 6.75,
 'FDT51': 11.65,
 'FDT52': 9.695,
 'FDT55': 13.6,
 'FDT56': 16.0,
 'FDT57': 15.2,
 'FDT58': 9.0,
 'FDT59': 13.65,
 'FDT60': 12.0,
 'FDU01': 20.25,
 'FDU02': 13.35,
 'FDU03': 18.7,
 'FDU04': 7.93,
 'FDU07': 11.1,
 'FDU08': 10.3,
 'FDU09': 7.71,
 'FDU10': 10.1,
 'FDU11': 4.785,
 'FDU12': 15.5,
 'FDU13': 8.355,
 'FDU14': 17.75,
 'FDU15': 13.65,
 'FDU16': 19.25,
 'FDU19': 8.77,
 'FDU20': 19.35,
 'FDU21': 11.8,
 'FDU22': 12.35,
 'FDU23': 12.15,
 'FDU24': 6.78,
 'FDU25': 12.35,
 'FDU26': 16.7,
 'FDU27': 18.6,
 'FDU28': 19.2,
 'FDU31': 10.5,
 'FDU32': 8.785,
 'FDU33': 7.63,
 'FDU34': 18.25,
 'FDU35': 6.44,
 'FDU36': 6.15,
 'FDU37': 9.5,
 'FDU38': 10.8,
 'FDU39': 18.85,
 ...}

In [13]:
data.loc[ (data['Item_Weight'].isna()), 'Item_Weight'] = data[data['Item_Weight'].isna()].apply(lambda row: weight_dict[row['Item_Identifier']], axis=1)

In [14]:
#data[data['Item_Weight'].isna()]['Item_Identifier'].apply(lambda row: weight_dict[row['Item_Identifier']], axis=1)

In [15]:
#data[data['Item_Weight'].isna()]['Item_Identifier'].apply(lambda x: weight_dict[x])

In [16]:
data['Outlet_Size'].fillna(value = 'Medium', inplace=True) # Imputing Mode Value

### One Hot Encoding

In [17]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 14204 entries, 0 to 5680
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Item_Identifier            14204 non-null  object
 1   Item_Weight                14204 non-null  float64
 2   Item_Fat_Content           14204 non-null  object
 3   Item_Visibility            14204 non-null  float64
 4   Item_Type                  14204 non-null  object
 5   Item_MRP                   14204 non-null  float64
 6   Outlet_Identifier          14204 non-null  object
 7   Outlet_Establishment_Year  14204 non-null  int64
 8   Outlet_Size                14204 non-null  object
 9   Outlet_Location_Type       14204 non-null  object
 10  Outlet_Type                14204 non-null  object
 11  Item_Outlet_Sales          8523 non-null   object
 12  is_train                   14204 non-null  int64
dtypes: float64(3), int64(2), object(8)
memory usage: 1.5+ MB

In [18]:
col_ls = ['Item_Identifier', 'Item_Fat_Content',
       'Item_Type', 'Outlet_Identifier',
       'Outlet_Establishment_Year', 'Outlet_Size', 'Outlet_Location_Type',
       'Outlet_Type']

In [19]:
data = pd.get_dummies(data = data,columns = col_ls)

In [20]:
data.shape

(14204, 1614)

In [21]:
data.head()

,Item_Weight,Item_Visibility,Item_MRP,Item_Outlet_Sales,is_train,Item_Identifier_DRA12,Item_Identifier_DRA24,Item_Identifier_DRA59,Item_Identifier_DRB01,Item_Identifier_DRB13,...,Outlet_Size_High,Outlet_Size_Medium,Outlet_Size_Small,Outlet_Location_Type_Tier 1,Outlet_Location_Type_Tier 2,Outlet_Location_Type_Tier 3,Outlet_Type_Grocery Store,Outlet_Type_Supermarket Type1,Outlet_Type_Supermarket Type2,Outlet_Type_Supermarket Type3
0,9.30,0.016047,249.8092,3735.14,1,0,0,0,0,0,...,0,1,0,1,0,0,0,1,0,0
1,5.92,0.019278,48.2692,443.423,1,0,0,0,0,0,...,0,1,0,0,0,1,0,0,1,0
2,17.50,0.016760,141.6180,2097.27,1,0,0,0,0,0,...,0,1,0,1,0,0,0,1,0,0
3,19.20,0.000000,182.0950,732.38,1,0,0,0,0,0,...,0,1,0,0,0,1,1,0,0,0
4,8.93,0.000000,53.8614,994.705,1,0,0,0,0,0,...,1,0,0,0,0,1,0,1,0,0

### Min Max Scaling

In [22]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

In [23]:
data[['Item_Weight', 'Item_Visibility', 'Item_MRP']] = scaler.fit_transform(data[['Item_Weight', 'Item_Visibility', 'Item_MRP']])

### Train Test Split

##### Seperating labeled and unlabeled data.

In [24]:
train_df = data[ data['is_train'] == 1]
test_df = data[ data['is_train'] == 0]

In [25]:
train_df.shape, test_df.shape

((8523, 1614), (5681, 1614))

In [26]:
train_df.drop(['is_train'], inplace=True, axis=1)
test_df.drop(['is_train'], inplace=True, axis=1)
test_df.drop(['Item_Outlet_Sales'], inplace=True, axis=1)

C:\Users\sunil\anaconda3\lib\site-packages\pandas\core\frame.py:3997: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [27]:
train_df.columns[-1]

'Outlet_Type_Supermarket Type3'

In [28]:
train_df = train_df[ [col for col in train_df if col!='Item_Outlet_Sales'] + ['Item_Outlet_Sales']]

In [29]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(train_df.iloc[:,:-1],train_df['Item_Outlet_Sales'], test_size = 0.30,random_state = 1999)

In [30]:
X_train.shape,X_test.shape,train_df.shape,

((5966, 1612), (2557, 1612), (8523, 1613))

---
# Linear Regression

In [31]:
from sklearn.linear_model import LinearRegression

model = LinearRegression(fit_intercept=True, normalize=False, copy_X=True)

In [32]:
model.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [33]:
from sklearn.metrics import mean_squared_error,mean_absolute_error

In [34]:
y_pred = model.predict(X_test)

In [35]:
mse = mean_squared_error(y_test,y_pred)

In [36]:
import math
rmse = math.sqrt(mse)
rmse

26198859271468.617

---
# Decision Tree

In [42]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import r2_score

In [64]:
model = DecisionTreeRegressor(max_depth=8)
model.fit(X_train, y_train)

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=8,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=None, splitter='best')

In [65]:
y_pred = model.predict(X_test)
mse = mean_squared_error(y_test,y_pred)

In [66]:
import math
rmse = math.sqrt(mse)
rmse

1114.2025178296135

---
# Random Forest

In [52]:
from sklearn.ensemble import RandomForestRegressor

In [67]:
model = RandomForestRegressor()

model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [68]:
mse = mean_squared_error(y_test,y_pred)
rmse = math.sqrt(mse)
rmse

1145.775971961617

--- 
# LASSO

In [56]:
from sklearn.linear_model import LassoCV
model = LassoCV()
model.fit(X_train, y_train)

LassoCV(alphas=None, copy_X=True, cv=None, eps=0.001, fit_intercept=True,
        max_iter=1000, n_alphas=100, n_jobs=None, normalize=False,
        positive=False, precompute='auto', random_state=None,
        selection='cyclic', tol=0.0001, verbose=False)

In [70]:
y_pred = model.predict(X_test)

In [71]:
mse = mean_squared_error(y_test,y_pred)
rmse = math.sqrt(mse)
rmse

1145.775971961617

In [72]:
min(y_pred)

46.54607799999997

---
# XGBoost

In [73]:
from xgboost.sklearn import XGBRegressor 

model = XGBRegressor()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [74]:
mse = mean_squared_error(y_test,y_pred)

In [75]:
rmse = math.sqrt(mse)
rmse

1101.0518130571259

In [76]:
min(y_pred)

-765.7961

# Final Prediction

In [79]:
train1 = data[ data['is_train'] == 1]
test1 = data[ data['is_train'] == 0]

In [80]:
train1.drop(['is_train'], inplace=True, axis=1)
test1.drop(['is_train'], inplace=True, axis=1)
test1.drop(['Item_Outlet_Sales'], inplace=True, axis=1)

C:\Users\sunil\anaconda3\lib\site-packages\pandas\core\frame.py:3997: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [81]:
train1.head()

,Item_Weight,Item_Visibility,Item_MRP,Item_Outlet_Sales,Item_Identifier_DRA12,Item_Identifier_DRA24,Item_Identifier_DRA59,Item_Identifier_DRB01,Item_Identifier_DRB13,Item_Identifier_DRB24,...,Outlet_Size_High,Outlet_Size_Medium,Outlet_Size_Small,Outlet_Location_Type_Tier 1,Outlet_Location_Type_Tier 2,Outlet_Location_Type_Tier 3,Outlet_Type_Grocery Store,Outlet_Type_Supermarket Type1,Outlet_Type_Supermarket Type2,Outlet_Type_Supermarket Type3
0,0.282525,0.048866,0.927507,3735.14,0,0,0,0,0,0,...,0,1,0,1,0,0,0,1,0,0
1,0.081274,0.058705,0.072068,443.423,0,0,0,0,0,0,...,0,1,0,0,0,1,0,0,1,0
2,0.770765,0.051037,0.468288,2097.27,0,0,0,0,0,0,...,0,1,0,1,0,0,0,1,0,0
3,0.871986,0.000000,0.640093,732.38,0,0,0,0,0,0,...,0,1,0,0,0,1,1,0,0,0
4,0.260494,0.000000,0.095805,994.705,0,0,0,0,0,0,...,1,0,0,0,0,1,0,1,0,0

In [82]:
test1.head()

,Item_Weight,Item_Visibility,Item_MRP,Item_Identifier_DRA12,Item_Identifier_DRA24,Item_Identifier_DRA59,Item_Identifier_DRB01,Item_Identifier_DRB13,Item_Identifier_DRB24,Item_Identifier_DRB25,...,Outlet_Size_High,Outlet_Size_Medium,Outlet_Size_Small,Outlet_Location_Type_Tier 1,Outlet_Location_Type_Tier 2,Outlet_Location_Type_Tier 3,Outlet_Type_Grocery Store,Outlet_Type_Supermarket Type1,Outlet_Type_Supermarket Type2,Outlet_Type_Supermarket Type3
0,0.964275,0.023036,0.325012,0,0,0,0,0,0,0,...,0,1,0,1,0,0,0,1,0,0
1,0.222983,0.117018,0.237819,0,0,0,0,0,0,0,...,0,1,0,0,1,0,0,1,0,0
2,0.598095,0.303221,0.893316,0,0,0,0,0,0,0,...,0,1,0,0,0,1,1,0,0,0
3,0.164335,0.046860,0.525233,0,0,0,0,0,0,0,...,0,1,0,0,1,0,0,1,0,0
4,0.538553,0.361153,0.861381,0,0,0,0,0,0,0,...,0,1,0,0,0,1,0,0,0,1

In [83]:
train1 = train1[ [col for col in train1 if col!='Item_Outlet_Sales'] + ['Item_Outlet_Sales']]

In [84]:
X_train = train1.iloc[:,:-1]
y_train = train1.iloc[:,-1]
X_test = test1

In [85]:
y_train.shape

(8523,)

In [86]:
model = XGBRegressor()
model.fit(X_train, y_train) 
y_pred = model.predict(X_test)

In [87]:
y_pred

array([1688.916 , 1356.9481,  834.9644, ..., 1774.6781, 3387.772 ,
       1543.2808], dtype=float32)

# Replacing negative values
model = model = DecisionTreeRegressor(max_depth=8)

model.fit(X_train, y_train)
y_pred = model.predict(X_test.iloc[index])

In [91]:
submit = sample_sub.copy()

In [89]:
submit['Item_Outlet_Sales'] = y_pred

In [94]:
submit.iloc[5572]

Item_Identifier        NCH43
Outlet_Identifier     OUT010
Item_Outlet_Sales    7.51194
Name: 5572, dtype: object

In [985]:
submit.to_csv(r"D:\Data Science Course\Projects\Analytics vidya\Big Mart Sales Prediction\submit.csv", index=False)

In [986]:
min(submit['Item_Outlet_Sales'])

7.5119428634643555